FROM rancher/server:v1.1.4
COPY cadvisor-v0.24.1/cadvisor.tar.gz /usr/share/cattle/artifacts/cadvisor.tar.gz
ADD https://github.com/rancher/cluster-manager/releases/download/v0.1.6/cluster-manager /usr/bin/
