FROM rancher/server:v1.1.4
COPY cadvisor-v0.24.1/cattle-resources-0.5.0-SNAPSHOT.jar /usr/share/cattle/58488b81592773dcae114770406e3e1b/WEB-INF/lib/
ADD https://github.com/rancher/cluster-manager/releases/download/v0.1.6/cluster-manager /usr/bin/
